<?php

namespace App\Console\Commands;

use App\Models\Camera;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SyncGo2RtcConfig extends Command
{
    protected $signature = 'go2rtc:sync';

    protected $description = 'Generate go2rtc.yaml from the cameras table (never prints RTSP passwords)';

    public function handle(): int
    {
        $configPath = $this->resolveConfigPath();

        $host = $this->host();
        $apiPort = (int) (env('GO2RTC_API_PORT', '1984'));
        $rtspPort = (int) (env('GO2RTC_RTSP_PORT', '8554'));
        $webrtcPort = (int) (env('GO2RTC_WEBRTC_PORT', '8555'));

        $cameras = Camera::query()->orderBy('id')->get();

        $streams = [];
        $activeCount = 0;
        foreach ($cameras as $camera) {
            $main = $camera->effective_main_url;
            $sub = $camera->effective_sub_url;
            $enabled = $camera->status === 'active';
            if ($enabled) {
                $activeCount++;
            }

            $streams[] = $this->streamEntry("cam{$camera->id}_main", $main, $enabled);
            if (trim($main) !== trim($sub)) {
                $streams[] = $this->streamEntry("cam{$camera->id}_sub", $sub, $enabled);
            } else {
                // Single URL: still expose cam{ID}_sub so the grid always has a sub-stream name.
                $streams[] = $this->streamEntry("cam{$camera->id}_sub", $sub, $enabled, true);
            }
        }

        if (count($streams) === 0) {
            $this->error('No cameras found in the database.');

            return self::FAILURE;
        }

        $lines = [];
        $lines[] = '# Auto-generated by `php artisan go2rtc:sync`. Do not edit by hand.';
        $lines[] = '# Edits to the cameras table require re-running the sync command.';
        $lines[] = '';
        $lines[] = 'api:';
        $lines[] = "  listen: \":{$apiPort}\"  # LAN WebUI + HTTP API";
        $apiUser = env('GO2RTC_API_USERNAME', '');
        $apiPass = env('GO2RTC_API_PASSWORD', '');
        if ($apiUser !== '' && $apiPass !== '') {
            $lines[] = '  # Basic auth (from .env). local_auth also protects localhost.';
            $lines[] = '  username: '.$this->scalar($apiUser);
            $lines[] = '  password: '.$this->scalar($apiPass);
            $lines[] = '  local_auth: true';
        } else {
            $lines[] = '  # TODO(security): set GO2RTC_API_USERNAME/GO2RTC_API_PASSWORD in .env,';
            $lines[] = '  # or proxy /api through Laravel. go2rtc /api exposes source URLs incl. credentials.';
        }
        $lines[] = '';
        $lines[] = 'rtsp:';
        $lines[] = "  listen: \"127.0.0.1:{$rtspPort}\"  # local restream for AI worker";
        $lines[] = '';
        $lines[] = 'webrtc:';
        $lines[] = "  listen: \":{$webrtcPort}\"  # TCP+UDP";
        $lines[] = '  candidates:';
        $lines[] = "    - \"{$host}:{$webrtcPort}\"";
        $lines[] = '';
        $lines[] = 'streams:';
        foreach ($streams as $entry) {
            $lines[] = $entry;
        }
        $lines[] = '';

        $yaml = implode("\n", $lines);

        File::ensureDirectoryExists(dirname($configPath));
        File::put($configPath, $yaml);

        $displayPath = realpath($configPath) ?: $configPath;
        $this->info("[OK] go2rtc config written: {$displayPath}");
        $this->line("Active cameras: {$activeCount} / ".count($cameras).' (streams: '.count($streams).')');
        $this->line("Host used for webrtc.candidates: {$host}:{$webrtcPort}");
        $this->info('Stream names: '.$cameras->pluck('id')->map(fn ($id) => "cam{$id}")->implode(', '));

        return self::SUCCESS;
    }

    private function streamEntry(string $name, string $url, bool $enabled, bool $isAlias = false): string
    {
        $line = "{$name}: ".$this->scalar($url);
        if (! $enabled) {
            $line = '# '.$line.'  # camera inactive';
        } elseif ($isAlias) {
            $line .= '  # same URL as _main (only single rtsp_url configured)';
        }

        return '  '.$line;
    }

    private function resolveConfigPath(): string
    {
        $path = env('GO2RTC_CONFIG_PATH', '../go2rtc/go2rtc.yaml');
        if (str_starts_with($path, '/') || preg_match('/^[A-Za-z]:[\\\\\\/]/', $path)) {
            return $path;
        }

        return base_path($path);
    }

    private function host(): string
    {
        $envHost = env('GO2RTC_HOST', '');
        if ($envHost !== '') {
            return $envHost;
        }

        $candidates = [];
        if (function_exists('net_get_interfaces')) {
            foreach (net_get_interfaces() as $iface) {
                foreach ($iface['unicast'] ?? [] as $addr) {
                    $ip = $addr['address'] ?? null;
                    if (is_string($ip) && filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)
                        && ! filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE)
                        && ! str_starts_with($ip, '169.254.')) {
                        $candidates[] = $ip;
                    }
                }
            }
        }

        $ip = $candidates[0] ?? gethostbyname(gethostname());
        if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) === false
            || filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false) {
            $ip = '127.0.0.1';
            $this->warn('Could not detect a LAN IP automatically; set GO2RTC_HOST in .env (e.g. your LAN IP) '
                .'so WebRTC candidates work. Using 127.0.0.1 as fallback.');
        }

        return $ip;
    }

    private function scalar(string $value): string
    {
        // Single-quote YAML scalars so URLs with ":/@?#" are never mis-parsed.
        return "'".str_replace("'", "''", $value)."'";
    }
}
